u19268468_HW03/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u19268468_HW03.Models;

namespace u19268468_HW03.Controllers
{
    public class AuthorsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: Authors
        public async Task<ActionResult> Index()
        {
            return View(await db.authors.ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(authors);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }

            return View(authors);
        }

        // GET: Authors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authors).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }
            return View(authors);
        }

        // GET: Authors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            authors authors = await db.authors.FindAsync(id);
            db.authors.Remove(authors);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsBooksCIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u19268468_HW03/Controllers/BorrowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u19268468_HW03.Models;

namespace u19268468_HW03.Controllers
{
    public class BorrowsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: Borrows
        public async Task<ActionResult> Index()
        {
            var borrows = db.borrows.Include(b => b.books).Include(b => b.students);
            return View(await borrows.ToListAsync());
        }

        // GET: Borrows/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // GET: Borrows/Create
        public ActionResult Create()
        {
            ViewBag.bookId = new SelectList(db.books, "bookId", "name");
            ViewBag.studentId = new SelectList(db.students, "studentId", "name");
            return View();
        }

        // POST: Borrows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.borrows.Add(borrows);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: Borrows/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // POST: Borrows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrows).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: Borrows/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // POST: Borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            borrows borrows = await db.borrows.FindAsync(id);
            db.borrows.Remove(borrows);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u19268468_HW03/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u19268468_HW03.Models;

namespace u19268468_HW03.Controllers
{
    public class TypesController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: Types
        public async Task<ActionResult> Index()
        {
            return View(await db.types.ToListAsync());
        }

        // GET: Types/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // GET: Types/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Types/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.types.Add(types);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }

            return View(types);
        }

        // GET: Types/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: Types/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.Entry(types).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }
            return View(types);
        }

        // GET: Types/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: Types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            types types = await db.types.FindAsync(id);
            db.types.Remove(types);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsBooksCIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u19268468_HW03/Views/Maintain/MaintainCIndex.cshtml
@model u19268468_HW03.Models.MaintainModel
@{
    ViewBag.Title = "MaintainCIndex";
}

<h2 style="font-family:Rockwell">Maintain </h2>
<p> Here you will find information regarding the authors, book types and the dates books were lent and returned. 
    The authors table showcases the authors infomration. The types table showcases the different book types that the library offers. 
    Finally, the borrows table showcases who borrowed the book, the book borrowed, date it was lent and the return date. </p>
<br />
<br />

<main>
    <div class="row">
        @*Authors Section*@
        <section class="col-md-6">
            <div class="row">
                <h4 class="col-md-10">Authors</h4>
                <button type="button" class="btn btn-outline-secondary col-md-2 btn-sm" href="@Url.Action("Create", "Authors")">Create</button>
            </div> <br/>

            <table class="table table-warning table-striped table-hover">
                <thead style="background-color: lightgray">
                    <tr>
                        <th> ID </th>
                        <th> Name </th>
                        <th> Surname </th>
                        <th></th>
                    </tr>
                </thead>

                @foreach (var item in Model.Authors)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.authorId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.surname)
                            </td>
                            <td>
                                <a href="#" class="edit-link" data-url="@Url.Action("Edit", "Authors", new {id = item.authorId})">Update</a>
                                <a href="#" class="edit-link" data-url="@Url.Action("Delete", "Authors", new {id = item.authorId})">Delete</a>
                            </td>
                        </tr>
                    </tbody>
                }

            </table>

            @*<ul class="pagination pagination-sm">
                    @{
                        if(!Model.IsFirstPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("ReportArchiveCIndex", "ReportArchive", new {pageIndex = Model.PageNumber -1})>
                                    Prev
                                </a>
                            </li>
                        }
                        if(!Model.IsLastPage)
                        {
                            <li>
                                <a class="page-link" href="@Url.Action("ReportArchiveCIndex", "ReportArchive", new {pageIndex = Model.PageNumber +1})">
                                    Next
                                </a>
                            </li>
                        }
                    }
                </ul>*@
        </section>

        @*Types Section*@
        <section class="col-md-6">
            <div class="row">
                <h4 class="col-md-10">Types</h4>
                <button type="button" class="btn btn-outline-secondary col-md-2 btn-sm" href="@Url.Action("Create", "Types")">Create</button>
            </div><br />

            <table class="table table-warning table-striped table-hover">
                <thead style="background-color: lightgray">
                    <tr>
                        <th> ID </th>
                        <th> Book Type </th>
                        <th></th>
                    </tr>
                </thead>

                @foreach (var item in Model.Types)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.typeId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                <a href="#" class="edit-link" data-url="@Url.Action("Edit", "Types", new {id = item.typeId})">Update</a>
                                <a href="#" class="edit-link" data-url="@Url.Action("Delete", "Types", new {id = item.typeId})">Delete</a>
                            </td>
                        </tr>
                    </tbody>

                }
            </table>

            @*<ul class="pagination pagination-sm">
                    @{
                        if(!Model.IsFirstPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("ReportArchiveCIndex", "ReportArchive", new {pageIndex = Model.PageNumber -1})>
                                    Prev
                                </a>
                            </li>
                        }
                        if(!Model.IsLastPage)
                        {
                            <li>
                                <a class="page-link" href="@Url.Action("ReportArchiveCIndex", "ReportArchive", new {pageIndex = Model.PageNumber +1})">
                                    Next
                                </a>
                            </li>
                        }
                    }
                </ul>*@
        </section>
    </div>


    @*Borrows Section*@
<section class="col-md-12">
    <div class="row">
        <h4 class="col-md-10">Borrows</h4>
        <button type="button" class="btn btn-outline-secondary col-md-2 btn-sm" href="@Url.Action("Create", "Borrows")">Create</button>
    </div>
    <br />

    <table class="table table-warning table-striped table-hover">
        <thead style="background-color: lightgray">
            <tr>
                <th> ID </th>
                <th> Student Name </th>
                <th> Book Name </th>
                <th> Taken Date </th>
                <th> Reurn Date </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model.Borrows)
        {
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.borrowId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.students.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.books.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.takenDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.broughtDate)
                    </td>
                    <td>
                        <a href="#" class="edit-link" data-url="@Url.Action("Edit", "Authors", new {id = item.borrowId})">Update</a>
                        <a href="#" class="edit-link" data-url="@Url.Action("Delete", "Authors", new {id = item.borrowId})">Delete</a>
                    </td>
                </tr>
            </tbody>

        }
    </table>

    @*<ul class="pagination pagination-sm">
            @{
                if(!Model.IsFirstPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("ReportArchiveCIndex", "ReportArchive", new {pageIndex = Model.PageNumber -1})>
                            Prev
                        </a>
                    </li>
                }
                if(!Model.IsLastPage)
                {
                    <li>
                        <a class="page-link" href="@Url.Action("ReportArchiveCIndex", "ReportArchive", new {pageIndex = Model.PageNumber +1})">
                            Next
                        </a>
                    </li>
                }
            }
        </ul>*@
                                                                                
    <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Complete Below</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal-content">
                </div>
            </div>
        </div>
    </div>

</section>
</main>

<script>
    $(function () {
        // Function to handle Edit link click event in the Combined View and Details modal
        $(".edit-link, .edit-link-in-modal").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });

        // Function to handle form submission within the modal
        $("#modal-content").on("submit", "form", function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr("action");
            var formData = form.serialize();

            $.post(url, formData, function (data) {
                $("#myModal").modal("hide");
                location.reload();
            });
        });

        // Function to handle other links (details, delete, create) within the modal
        $(".details-link, .delete-link, .create-link, .create-lookup-link").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });
    });
</script>