u19268468_HW03/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u19268468_HW03.Models;

namespace u19268468_HW03.Controllers
{
    public class BooksController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: Books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: Books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: Books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsBooksCIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u19268468_HW03/Controllers/Combined Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u19268468_HW03.Models;
using Newtonsoft.Json;


namespace u19268468_HW03.Controllers
{
    public class HomeController : Controller
    {
        int numberElementPerPage = 10;
        private LibraryEntities db = new LibraryEntities();
        LibraryEntities db1 = new LibraryEntities();

        //Get: StudentsBooksCIndex
        public async Task<ActionResult> StudentsBooksCIndex(int pageIndex=1)
        {
            var viewModel = new StudentsBooksModel
            {
                Students = await db.students.Include(s => s.borrows).ToListAsync(),
                Books = await db.books.Include(s => s.types).Include(s => s.authors).ToListAsync()
            };

            return View(viewModel);
        }

        //GET: Students
        public async Task<ActionResult> StudentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // GET: students/Create
        public ActionResult StudentCreate()
        {
            return View();
        }

        // POST: students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentCreate([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }

            return View(students);
        }

        // GET: students/Edit/5
        public async Task<ActionResult> StudentEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentEdit([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }
            return View(students);
        }

        // GET: students/Delete/5
        public async Task<ActionResult> StudentDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentDeleteConfirmed(int id)
        {
            students students = db.students.Find(id);
            db.students.Remove(students);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsBooksCIndex", "Home");
        }

        //GET: Books 
        public async Task<ActionResult> BooksDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult BooksCreate()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BooksCreate([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> BooksEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BooksEdit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> BooksDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BooksDeleteConfirmed(int id)
        {
            books books = db.books.Find(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsBooksCIndex", "Home");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u19268468_HW03/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u19268468_HW03.Models;

namespace u19268468_HW03.Controllers
{
    public class StudentsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: Students
        public async Task<ActionResult> Index()
        {
            return View(await db.students.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }

            return View(students);
        }

        // GET: Students/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsBooksCIndex", "Home");
            }
            return View(students);
        }

        // GET: Students/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            students students = await db.students.FindAsync(id);
            db.students.Remove(students);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsBooksCIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u19268468_HW03/Views/Home/StudentsBooksCIndex.cshtml
@model u19268468_HW03.Models.StudentsBooksModel
@{
    ViewBag.Title = "StudentsBooksCIndex";
}

<h2 style="font-family:Rockwell">Students and Books </h2>
<p> Here you will find information regarding the students information, as well as the books on can borrow at the library.</p>
<br />
<br />

<head>
    <style>
        .back-to-top {
            position: fixed;
            bottom: 25px;
            right: 25px;
            display: none;
        }
    </style>
</head>
<main>
    <div class="row">
        <section class="col-md-6">
            <div class="row">
                <h4 class="col-md-10">Students</h4>
                <button type="button" class="btn btn-outline-secondary col-md-2 btn-sm" href="@Url.Action("Create", "Students")">Create</button>
            </div>
            <br />

            <table class="table table-warning table-striped table-hover">
                <thead style="background-color: lightgray">
                    <tr>
                        <th> ID </th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Birthdate</th>
                        <th>Gender</th>
                        <th>Class</th>
                        <th>Points</th>
                    </tr>
                </thead>
                <tbody id="StudentTable">
                    @foreach (var item in Model.Students)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.studentId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.surname)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.birthdate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.gender)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.@class)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.point)
                            </td>
                        </tr>
                    }
                </tbody>

            </table>

            <div class="col-md-12 text-center">
                <div class="pagination" id="studentPagination">
                    <button class="btn btn-secondary" id="prevStudentPage">Previous</button>
                    <span id="studentPageInfo">Page <span id="currentStudentPage">1</span> of <span id="totalStudentPages">1</span></span>
                    <button class="btn btn-primary" id="nextStudentPage">Next</button>
                </div>
            </div>
        </section>

        <section class="col-md-6">
            <div class="row">
                <h4 class="col-md-10">Books</h4>
                <button type="button" class="btn btn-outline-secondary col-md-2 btn-sm" href="@Url.Action("Create", "Books")">Create</button>
            </div>
            <br />

            <table class="table table-warning table-striped table-hover">
                <thead style="background-color: lightgray">
                    <tr>
                        <th> ID </th>
                        <th> Book Name </th>
                        <th> Page Count </th>
                        <th> Points </th>
                        <th> Author Name </th>
                        <th> Book Type </th>
                    </tr>
                </thead>
                <tbody id="BookTable">
                    @foreach (var item in Model.Books)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.bookId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.pagecount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.point)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.authors.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.types.name)
                            </td>
                        </tr>

                    }
                </tbody>

            </table>

            <div class="pagination" id="bookPagination">
                <button class="btn btn-secondary" id="prevBookPage">Previous</button>
                <span id="bookPageInfo">Page <span id="currentBookPage">1</span> of <span id="totalBookPages">1</span></span>
                <button class="btn btn-primary" id="nextBookPage">Next</button>
            </div>
        </section>
    </div>

    <a id="back-to-top" href="#" class="btn btn-light btn-lg back-to-top" role="button"><i class="fas fa-chevron-up"></i></a>
</main>

<script>
    $(document).ready(function () {
        $(window).scroll(function () {
            if ($(this).scrollTop() > 50) {
                $('#back-to-top').fadeIn();
            } else {
                $('#back-to-top').fadeOut();
            }
        });
        // scroll body to 0px on click
        $('#back-to-top').click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 400);
            return false;
        });
    });
    //PAGINATION

    document.addEventListener("DOMContentLoaded", function () {
        const studentTableRows = document.querySelectorAll("#StudentTable tr");
        const bookTableRows = document.querySelectorAll("#BookTable tr");
        const itemsPerPage = 5; // Adjust the number of items per page as needed.
        let currentStudentPage = 1;
        let currentBookPage = 1;

        // Pagination functions for Student Table
        function showStudentPage(page) {
            const startIndex = (page - 1) * itemsPerPage;
            const endIndex = startIndex + itemsPerPage;

            for (let i = 0; i < studentTableRows.length; i++) {
                studentTableRows[i].style.display = (i >= startIndex && i < endIndex) ? "table-row" : "none";
            }
        }

        function updateStudentPaginationInfo() {
            const totalStudentPages = Math.ceil(studentTableRows.length / itemsPerPage);
            document.getElementById("currentStudentPage").textContent = currentStudentPage;
            document.getElementById("totalStudentPages").textContent = totalStudentPages;
        }

        function prevStudentPage() {
            if (currentStudentPage > 1) {
                currentStudentPage--;
                showStudentPage(currentStudentPage);
                updateStudentPaginationInfo();
            }
        }

        function nextStudentPage() {
            const totalStudentPages = Math.ceil(studentTableRows.length / itemsPerPage);
            if (currentStudentPage < totalStudentPages) {
                currentStudentPage++;
                showStudentPage(currentStudentPage);
                updateStudentPaginationInfo();
            }
        }

        // Pagination functions for Book Table
        function showBookPage(page) {
            const startIndex = (page - 1) * itemsPerPage;
            const endIndex = startIndex + itemsPerPage;

            for (let i = 0; i < bookTableRows.length; i++) {
                bookTableRows[i].style.display = (i >= startIndex && i < endIndex) ? "table-row" : "none";
            }
        }

        function updateBookPaginationInfo() {
            const totalBookPages = Math.ceil(bookTableRows.length / itemsPerPage);
            document.getElementById("currentBookPage").textContent = currentBookPage;
            document.getElementById("totalBookPages").textContent = totalBookPages;
        }

        function prevBookPage() {
            if (currentBookPage > 1) {
                currentBookPage--;
                showBookPage(currentBookPage);
                updateBookPaginationInfo();
            }
        }

        function nextBookPage() {
            const totalBookPages = Math.ceil(bookTableRows.length / itemsPerPage);
            if (currentBookPage < totalBookPages) {
                currentBookPage++;
                showBookPage(currentBookPage);
                updateBookPaginationInfo();
            }
        }

        // Initialize both tables and their pagination controls
        showStudentPage(currentStudentPage);
        updateStudentPaginationInfo();
        showBookPage(currentBookPage);
        updateBookPaginationInfo();

        // Add event listeners for pagination buttons for both tables
        document.getElementById("studentPagination").querySelector("#prevStudentPage").addEventListener("click", prevStudentPage);
        document.getElementById("studentPagination").querySelector("#nextStudentPage").addEventListener("click", nextStudentPage);
        document.getElementById("bookPagination").querySelector("#prevBookPage").addEventListener("click", prevBookPage);
        document.getElementById("bookPagination").querySelector("#nextBookPage").addEventListener("click", nextBookPage);
    });
</script>